/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar.vue')['default']
    ContentBlock: typeof import('./src/components/content-block.vue')['default']
    ErrorBlock: typeof import('./src/components/blocks/error-block.vue')['default']
    IconAdd: typeof import('./src/components/icons/icon-add.vue')['default']
    IconCross: typeof import('./src/components/icons/icon-cross.vue')['default']
    IconDelete: typeof import('./src/components/icons/icon-delete.vue')['default']
    IconDown: typeof import('./src/components/icons/icon-down.vue')['default']
    IconLang: typeof import('./src/components/icons/icon-lang.vue')['default']
    IconLoading: typeof import('./src/components/icons/icon-loading.vue')['default']
    IconMenu: typeof import('./src/components/icons/icon-menu.vue')['default']
    IconRefresh: typeof import('./src/components/icons/icon-refresh.vue')['default']
    IMdiCloudPercent: typeof import('~icons/mdi/cloud-percent')['default']
    IMdiThermometerAuto: typeof import('~icons/mdi/thermometer-auto')['default']
    IMdiWaterPercent: typeof import('~icons/mdi/water-percent')['default']
    MessageBlock: typeof import('./src/components/blocks/message-block.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NavIcon: typeof import('./src/components/navbar/nav-icon.vue')['default']
    NavMenu: typeof import('./src/components/navbar/nav-menu.vue')['default']
    NavNarrowMenu: typeof import('./src/components/navbar/nav-narrow-menu.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    SwitchBox: typeof import('./src/components/switch-box.vue')['default']
    Terms: typeof import('./src/components/terms.vue')['default']
  }
}
